fix: install type check before download

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -13,35 +13,50 @@ function fail() {
 	exit 1
 }
 
-function download() {
-	local url
-	local os_name
+# ref installs not supported
+if [ "$ASDF_INSTALL_TYPE" != "version" ]; then
+	fail "supports release installs only. See \"asdf list all $TOOL_NAME\" for a list of supported versions."
+fi
 
-	case $(uname -s) in
-	Linux*)
-		os_name="linux"
-		;;
-	Darwin*)
-		os_name="macos"
-		;;
-	*)
-		fail "Script only supports macOS and Ubuntu"
-		;;
-	esac
-	url="${GH_REPO}/releases/download/v${ASDF_INSTALL_VERSION}/firebase-tools-${os_name}"
-
-	printf "%s\\n" "* downloading ${TOOL_NAME} ${ASDF_INSTALL_VERSION} from ${url}"
-	status_code=$(curl -X GET \
-		--write-out "%{http_code}" \
-		--progress-bar \
-		-Lo "${ASDF_DOWNLOAD_PATH}/${TOOL_NAME}" \
-		"${url}")
-
-	if [[ ${status_code} -eq 404 ]]; then
-		rm -rf "${ASDF_DOWNLOAD_PATH}"
-		fail "An error occurred. firebase-tools may not have been found for version ${ASDF_INSTALL_VERSION}. Full versions are required, not just major version numbers."
+if [ "$ASDF_INSTALL_TYPE" == "version" ]; then
+	# validate version(non-ref) is in list-all versions
+	results="$(asdf list all v)"
+	if ! grep -q "^$ASDF_INSTALL_VERSION$" <<<"$results"; then
+		fail "version \"$ASDF_INSTALL_VERSION\" not supported. \"asdf list all $TOOL_NAME\" will list available versions."
 	fi
-	printf "%s\\n" "* Downloaded to ${ASDF_DOWNLOAD_PATH}/${TOOL_NAME}"
-}
+
+	# Warn if user attempts to install a version(non-ref) that the plugin might not support
+	if awk "BEGIN {exit !($ASDF_INSTALL_VERSION < $MIN_SUPPORTED_VERSION)}"; then
+		printf "* WARNING asdf-%s was developed for versions \"%s\" and later.\\n" "$TOOL_NAME" "$MIN_SUPPORTED_VERSION"
+		printf "          Versions before this are not guaranteed to work.\\n"
+	fi
+fi
+
+os_name="default"
+case $(uname -s) in
+Linux*)
+	os_name="linux"
+	;;
+Darwin*)
+	os_name="macos"
+	;;
+*)
+	fail "Script only supports macOS and Ubuntu"
+	;;
+esac
+url="${GH_REPO}/releases/download/v${ASDF_INSTALL_VERSION}/firebase-tools-${os_name}"
+
+printf "%s\\n" "* Downloading ${TOOL_NAME} ${ASDF_INSTALL_VERSION} from ${url}"
+status_code=$(curl -X GET \
+	--write-out "%{http_code}" \
+	--progress-bar \
+	-Lo "${ASDF_DOWNLOAD_PATH}/${TOOL_NAME}" \
+	"${url}")
+
+if [[ ${status_code} -eq 404 ]]; then
+	rm -rf "${ASDF_DOWNLOAD_PATH}"
+	fail "An error occurred. firebase-tools may not have been found for version ${ASDF_INSTALL_VERSION}. Full versions are required, not just major version numbers."
+fi
+printf "%s\\n" "* Downloaded to ${ASDF_DOWNLOAD_PATH}/${TOOL_NAME}"
 
 download
