feat: rewrite & simplify plugin (#25)

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -5,26 +5,50 @@ set -euo pipefail
 current_script_path="${BASH_SOURCE[0]}"
 plugin_dir="$(dirname "$(dirname "$current_script_path")")"
 
-# shellcheck source=../lib/utils.bash
-source "${plugin_dir}/lib/utils.bash"
+# shellcheck source=../lib/envs.bash
+. "${plugin_dir}/lib/envs.bash"
 
-function download() {
-	local filename="firebase"
-	local url
-	url="$(get_github_repo)/releases/download/v${ASDF_INSTALL_VERSION}/firebase-tools-$(get_os_name)"
-
-	log_info "⏬  downloading ${filename} ${ASDF_INSTALL_VERSION} from ${url}"
-	status_code=$(curl -X GET \
-		--write-out "%{http_code}" \
-		--progress-bar \
-		-Lo "${ASDF_DOWNLOAD_PATH}/${filename}" \
-		"${url}")
-
-	if [[ ${status_code} -eq 404 ]]; then
-		rm -rf "${ASDF_DOWNLOAD_PATH}"
-		log_failure_and_exit "An error occurred. firebase-tools may not have been found for version ${ASDF_INSTALL_VERSION}. Full versions are required, not just major version numbers."
-	fi
-	log_success "downloaded!"
+function fail() {
+	printf "* ERROR: asdf-%s %s\\n" "$TOOL_NAME" "$*"
+	exit 1
 }
 
-download
+# ref installs not supported
+if [ "$ASDF_INSTALL_TYPE" != "version" ]; then
+	fail "supports release installs only. See \"asdf list all $TOOL_NAME\" for a list of supported versions."
+fi
+
+if [ "$ASDF_INSTALL_TYPE" == "version" ]; then
+	# validate version(non-ref) is in list-all versions
+	results="$(asdf list all $TOOL_NAME)"
+	if ! grep -q "^$ASDF_INSTALL_VERSION$" <<<"$results"; then
+		fail "version \"$ASDF_INSTALL_VERSION\" not supported. \"asdf list all $TOOL_NAME\" will list available versions."
+	fi
+fi
+
+os_name="default"
+case $(uname -s) in
+Linux*)
+	os_name="linux"
+	;;
+Darwin*)
+	os_name="macos"
+	;;
+*)
+	fail "Script only supports macOS and Ubuntu"
+	;;
+esac
+url="${GH_REPO}/releases/download/v${ASDF_INSTALL_VERSION}/firebase-tools-${os_name}"
+
+printf "* Downloading %s@%s from %s\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION" "$url"
+status_code=$(curl -X GET \
+	--write-out "%{http_code}" \
+	--progress-bar \
+	-Lo "${ASDF_DOWNLOAD_PATH}/${TOOL_NAME}" \
+	"${url}")
+
+if [[ ${status_code} -eq 404 ]]; then
+	rm -rf "${ASDF_DOWNLOAD_PATH}"
+	fail "An error occurred. firebase-tools may not have been found for version ${ASDF_INSTALL_VERSION}. Full versions are required, not just major version numbers."
+fi
+printf "%s\\n" "* Downloaded to ${ASDF_DOWNLOAD_PATH}/${TOOL_NAME}"
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,38 +2,40 @@
 
 set -euo pipefail
 
-current_script_path="${BASH_SOURCE[0]}"
-plugin_dir="$(dirname "$(dirname "$current_script_path")")"
+current_script_path=${BASH_SOURCE[0]}
+plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
-# shellcheck source=../lib/utils.bash
-source "${plugin_dir}/lib/utils.bash"
+# shellcheck source=../lib/envs.bash
+. "${plugin_dir}/lib/envs.bash"
 
-function install_firebase() {
+function fail() {
+	printf "* ERROR: asdf-%s %s\\n" "$TOOL_NAME" "$*"
+	exit 1
+}
+
+# download & install
+(
 	# if not asdf version with asdf_download_path then call download script here
 	if [ -z "${ASDF_DOWNLOAD_PATH:-}" ]; then
 		tmp_download_dir=$(mktemp -d -t 'asdf_firebase_XXXXXX')
 		trap 'rm -rf "${tmp_download_dir}"' EXIT
-		log_info "ℹ️  run download script for older version of asdf"
+		printf "* run download script for older version of asdf"
 		export ASDF_DOWNLOAD_PATH="${tmp_download_dir}"
 
 		# download
 		bash "$(dirname "$0")/download"
 	fi
 
-	log_info "🚧  installing..."
-	# move executable
 	mkdir -p "${ASDF_INSTALL_PATH}/bin"
 	cp "${ASDF_DOWNLOAD_PATH}/firebase" "${ASDF_INSTALL_PATH}/bin"
+	printf "* Moved to %s\\n" "$ASDF_INSTALL_PATH"
 	chmod +rx "${ASDF_INSTALL_PATH}/bin/firebase"
-	# test executable
-	test -x "${ASDF_INSTALL_PATH}/bin/firebase" || log_failure_and_exit "Expected ${ASDF_INSTALL_PATH}/bin/firebase to be executable."
-	log_success "firebase-tools ${ASDF_INSTALL_VERSION} installed!"
-}
 
-if [ "${ASDF_INSTALL_TYPE}" != "version" ]; then
-	log_failure_and_exit "Please provide the firebase-tools version number you wish to install."
-fi
-
-check_dependencies "$(dirname "$0")/../lib/dependencies.txt" "failure"
-
-install_firebase
+	printf "* Testing if %s@%s is executable\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
+	tool_cmd="$(printf "%s\\n" "$TOOL_TEST" | cut -d' ' -f1)"
+	test -x "$ASDF_INSTALL_PATH/bin/$tool_cmd" || fail "Expected $ASDF_INSTALL_PATH/bin/$tool_cmd to be executable."
+	printf "* Success! %s@%s is ready for use.\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
+) || (
+	rm -rf "$ASDF_INSTALL_PATH"
+	fail "An error ocurred while installing $TOOL_NAME@$ASDF_INSTALL_VERSION"
+)
